// Generated by CoffeeScript 1.7.1
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    var title, url;
    if (tab) {
      title = tab.title;
      url = tab.url;
      return chrome.tabs.sendMessage(tab.id, {
        args: ""
      }, function(x, y, text) {
        return console.log(x, y, text);
      });
    }
  });

}).call(this);

//# sourceMappingURL=background.map
