// Generated by CoffeeScript 1.7.1
(function() {
  var handleContextMenu, handleMouseEvent, handleRequest, pinOnPage, sendDataToBackground;

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var cursorURL, modal, path, pin, _i, _len, _ref;
    console.dir(request.pins);
    if (request.pins && request.pins.length > 0) {
      _ref = request.pins;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pin = _ref[_i];
        pinOnPage(pin.x, pin.y, pin.text);
      }
    }
    path = chrome.extension.getURL('/imgs/logo/20.png');
    cursorURL = "url('" + path + "'),auto";
    $("body").css('cursor', cursorURL).mouseup(handleMouseEvent).bind('contextmenu.pageMark', handleContextMenu);
    if (!$("#page-mark-modal").length) {
      modal = $("<div id='page-mark-modal'/>");
      return $('body').append(modal);
    }
  });

  handleRequest = function(args) {
    return args;
  };

  handleMouseEvent = function(event) {
    var container, positionX, positionY;
    container = $('.page-mark');
    if (container.is(event.target) || (container.has(event.target).length > 0)) {
      return;
    }
    if (event.which === 1) {
      $('.page-mark .description').remove();
      positionX = event.pageX - 6;
      positionY = event.pageY - 6;
      pinOnPage(positionX, positionY, '');
      sendDataToBackground({
        x: positionX,
        y: positionY
      });
      $('.page-mark .input').focus();
      return $('.page-mark .submit').click(function() {
        var text;
        text = $(this).siblings('.input').val();
        sendDataToBackground({
          x: positionX,
          y: positionY,
          text: text
        });
        $(this).parent().parent().append("<p class='message'>" + text + "</p>");
        return $(this).parent().remove();
      });
    } else {
      if ($("#page-mark-modal").length) {
        $('#page-mark-modal').remove();
      }
      $(".page-mark .description").remove();
      $("body").css('cursor', "default").unbind('mouseup');
      return setTimeout(function() {
        return $("body").unbind('contextmenu.pageMark');
      }, 1);
    }
  };

  pinOnPage = function(positionX, positionY, text) {
    var pin, pinCollection, pinURL;
    pinURL = chrome.extension.getURL('/imgs/logo/32.png');
    pin = "<div class='pin page-mark' style='left:" + positionX + "px;top:" + positionY + "px'>\n	<img src='" + pinURL + "'/>\n</div>";
    if ($('#page-mark-pin-collection').length) {
      return $('#page-mark-pin-collection').append(pin);
    } else {
      pinCollection = $("<div/>").attr('id', 'page-mark-pin-collection').append(pin);
      return $('body').append(pinCollection);
    }
  };

  handleContextMenu = function(e) {
    return false;
  };

  sendDataToBackground = function(data) {
    return chrome.runtime.sendMessage({
      data: data
    });
  };

}).call(this);

//# sourceMappingURL=contentScripts.map
