// Generated by CoffeeScript 1.7.1
(function() {
  var handleContextMenu, handleMouseEvent, handleRequest;

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var cursorURL, path;
    path = chrome.extension.getURL('/imgs/logo/20.png');
    cursorURL = "url('" + path + "'),auto";
    return $("body").css('cursor', cursorURL).mouseup(handleMouseEvent).bind('contextmenu.pageMark', handleContextMenu);
  });

  handleRequest = function(args) {
    return args;
  };

  handleMouseEvent = function(event) {
    var pin, pinCollection, pinURL;
    if (event.which === 1) {
      pinURL = chrome.extension.getURL('/imgs/logo/32.png');
      pin = "<div style='position: absolute;left:" + (event.pageX - 6) + "px;top:" + (event.pageY - 6) + "px'>\n<img src='" + pinURL + "'/>\n</div>";
      if ($('#page-mark-pin-collection').length) {
        return $('#page-mark-pin-collection').append(pin);
      } else {
        pinCollection = $("<div></div>").attr('id', 'page-mark-pin-collection').append(pin);
        return $('body').append(pinCollection);
      }
    } else {
      $("body").css('cursor', "default").unbind('mouseup');
      return setTimeout(function() {
        return $("body").unbind('contextmenu.pageMark');
      }, 1);
    }
  };

  handleContextMenu = function(e) {
    return false;
  };

}).call(this);

//# sourceMappingURL=contentScripts.map
